export const LINKS = {
  GITHUB: 'https://github.com/AustinSpinazze',
  LINKEDIN: 'https://www.linkedin.com/in/austin-spinazze/',
  EMAIL: 'mailto:austin.spinazze@austinspinazze.dev',
  TWITTER: 'https://twitter.com/AustinSpinazze',
  INSTAGRAM: 'https://www.instagram.com/austinspinazzedev/',
};

export const WATER_BOT_CONTENT = [
  'Thousands have lived without love, not one without water. - W. H. Auden',
  'What do you call a fake noodle? An impasta! - Unknown',
  'In one drop of water are found all the secrets of all the oceans. - Kahlil Gibran',
  "What do you call a can of soda that's been in the fridge for too long? A Fizzy Lifter! - Unknown",
  'What do you call a fish that wears a bowtie? Sofishticated! - Unknown',
  'Why did the tomato turn red? Because it saw the salad dressing! - Unknown',
  'Water is the driving force of all nature. - Leonardo da Vinci',
  'Why was the math book sad? Because it had too many problems. - Unknown',
  "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels. - Unknown",
  'We never know the worth of water till the well is dry. - Thomas Fuller',
  'What do you get when you cross a snowman and a shark? Frostbite! - Unknown',
  "What do you call a fish that's good at basketball? Swish! - Unknown",
  'Whiskey is for drinking; water is for fighting over. - Mark Twain',
  'Nothing is softer or more flexible than water, yet nothing can resist it. - Lao Tzu',
  'What do you call a fish that wears a crown? Kingfish! - Unknown',
  "Why don't scientists trust atoms? Because they make up everything. - Unknown",
  'Why did the chicken cross the playground? To get to the other slide. - Unknown',
  'What do you get when you cross a snowman and a vampire? Frostbite! - Unknown',
  'Water is the soul of the Earth. - W. H. Jordan',
  'Why did the cookie go to the doctor? Because it was feeling crumbly. - Unknown',
  "What do you call a bicycle that's been left out in the rain? Rusty! - Unknown",
  "Why couldn't the bicycle stand up by itself? Because it was two-tired. - Unknown",
  'What did the grape say when it got stepped on all day? Nothing, it just let out a little wine. - Unknown',
  'Why was the belt sent to jail? For holding up the pants. - Unknown',
  'What do you call a cat that likes to eat lemons? Sour Puss! - Unknown',
  'What do you call a lazy kangaroo? A pouch potato! - Unknown',
  'What do you call a monkey in a suit? A business! - Unknown',
  'What do you call a baby monkey? A chimp off the old block! - Unknown',
];
